cluster:
  name: hub-a
  role: hub
  environment: homelab
  physicalHost: dell-r730xd

argocd:
  namespace: argocd
  destinationServer: https://kubernetes.default.svc

source:
  repoURL: https://github.com/0xdsqr/dsqr-dotdev.git
  targetRevision: refs/heads/master

applications:
  - cilium
  - metallb
  - metallb-config
  - traefik
  - metrics-server
  - kube-state-metrics
  - k8s-monitoring
  - external-secrets
  - external-secrets-config
  - dotdev-web
  - dotdev-studio
  - dotdev-labs
  - fidara
  - twt-web
  - twt-admin
