# hub-a Helm value overrides for Traefik.
service:
  annotations:
    metallb.io/address-pool: ingress
    metallb.io/loadBalancerIPs: 10.10.30.200

tlsStore:
  default:
    defaultCertificate:
      secretName: hub-a-traefik-origin-tls
