apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

labels:
  - pairs:
      app.kubernetes.io/part-of: dsqr-gitops

resources:
  - namespace.yaml
  - projects/platform.appproject.yaml
  - projects/dsqr.appproject.yaml
  - applications/platform-addons.applicationset.yaml
  - applications/dsqr-apps.applicationset.yaml
