apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-hub-a.clustersecretstore.yaml
  - ghcr-pull.clusterexternalsecret.yaml
  - argocd-fidara-repo.externalsecret.yaml
