apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-homelab
  labels:
    app.kubernetes.io/name: vault-homelab
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-secrets
    homelab.dev/owner: platform
    homelab.dev/tier: platform-addon
spec:
  provider:
    vault:
      server: http://10.10.30.107:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: homelab-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
