/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiscRouteImport } from './routes/misc'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAvatarUserIdFileNameRouteImport } from './routes/api/avatar.$userId.$fileName'

const MiscRoute = MiscRouteImport.update({
  id: '/misc',
  path: '/misc',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarUserIdFileNameRoute = ApiAvatarUserIdFileNameRouteImport.update({
  id: '/api/avatar/$userId/$fileName',
  path: '/api/avatar/$userId/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/misc': typeof MiscRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/avatar/$userId/$fileName': typeof ApiAvatarUserIdFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/misc': typeof MiscRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/avatar/$userId/$fileName': typeof ApiAvatarUserIdFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/misc': typeof MiscRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/avatar/$userId/$fileName': typeof ApiAvatarUserIdFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/misc'
    | '/posts/$slug'
    | '/posts'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/avatar/$userId/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/misc'
    | '/posts/$slug'
    | '/posts'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/avatar/$userId/$fileName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/misc'
    | '/posts/$slug'
    | '/posts/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/avatar/$userId/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MiscRoute: typeof MiscRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiAvatarUserIdFileNameRoute: typeof ApiAvatarUserIdFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/misc': {
      id: '/misc'
      path: '/misc'
      fullPath: '/misc'
      preLoaderRoute: typeof MiscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$userId/$fileName': {
      id: '/api/avatar/$userId/$fileName'
      path: '/api/avatar/$userId/$fileName'
      fullPath: '/api/avatar/$userId/$fileName'
      preLoaderRoute: typeof ApiAvatarUserIdFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MiscRoute: MiscRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiAvatarUserIdFileNameRoute: ApiAvatarUserIdFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
