global:
  domain: argocd.dsqr.dev

configs:
  params:
    server.insecure: "true"

crds:
  install: true
  keep: true

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.dsqr.dev
    path: /
    pathType: Prefix
    tls: false
