deployment:
  replicas: 1

service:
  type: LoadBalancer

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

ingressRoute:
  dashboard:
    enabled: true
