apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: dsqr-gitops
    homelab.dev/owner: platform
    homelab.dev/tier: gitops
    pod-security.kubernetes.io/enforce: baseline
