apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/part-of: dsqr-gitops
    homelab.dev/tier: platform
spec:
  description: Homelab cluster platform add-ons
  sourceRepos:
    - https://github.com/0xdsqr/dsqr-dotdev.git
    - https://argoproj.github.io/argo-helm
    - https://helm.cilium.io/
    - https://metallb.github.io/metallb
    - https://traefik.github.io/charts
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: cilium-secrets
    - server: https://kubernetes.default.svc
      namespace: metallb-system
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: observability
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
