set -euo pipefail

# shellcheck disable=SC2016
marker='Generated by `nix run .#gitopsGenerateApplications`'

usage() {
  cat <<'EOF'
Usage:
  gitops-generate-applications [--check] [--repo-root PATH]

Renders gitops/clusters/<cluster>/applications/*.yaml from
local YAML resources listed in gitops/clusters/<cluster>/applications/kustomization.yaml.

Options:
  --check      render into a temporary copy and fail if generated files differ
  --repo-root  repository root to render; defaults to the current directory
EOF
}

check=false
repo_root="$PWD"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      check=true
      shift
      ;;
    --repo-root)
      if [[ $# -lt 2 ]]; then
        echo "--repo-root requires a path" >&2
        exit 2
      fi
      repo_root="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

generate() {
  local root="$1"
  local clusters_dir="$root/gitops/clusters"
  local templates_dir="$root/gitops/templates/applications"

  if [[ ! -d "$clusters_dir" ]]; then
    echo "Missing clusters directory: $clusters_dir" >&2
    exit 1
  fi

  local argocd_namespace="argocd"
  local destination_server="https://kubernetes.default.svc"
  local values_repo_url="https://github.com/0xdsqr/dsqr-dotdev.git"
  local values_target_revision="master"

  local cluster_dir
  for cluster_dir in "$clusters_dir"/*; do
    [[ -d "$cluster_dir" ]] || continue
    local applications_dir="$cluster_dir/applications"
    local applications_kustomization="$applications_dir/kustomization.yaml"
    [[ -f "$applications_kustomization" ]] || continue

    local cluster
    cluster="$(basename "$cluster_dir")"

    find "$applications_dir" -maxdepth 1 -type f -name "*.yaml" ! -name "kustomization.yaml" -print |
      while IFS= read -r existing_file; do
        if grep -qF "$marker" "$existing_file"; then
          rm "$existing_file"
        fi
      done

    mapfile -t cluster_apps < <(
      yq -r '.resources[] | select(test("^[A-Za-z0-9._-]+\\.yaml$"))' "$applications_kustomization"
    )

    local app_name
    local app_file
    for app_file in "${cluster_apps[@]}"; do
      app_name="${app_file%.yaml}"
      local template_path
      template_path="$templates_dir/$app_name.yaml.tmpl"

      if [[ -z "$app_name" ]]; then
        echo "Cluster $cluster has an empty application entry" >&2
        exit 1
      fi

      if [[ ! -f "$template_path" ]]; then
        echo "Missing template: $template_path" >&2
        exit 1
      fi

      local values_common_file
      local values_overlay_file
      local values_overlay_dir
      values_common_file="gitops/manifests/$app_name/base/values-common.yaml"
      values_overlay_file="gitops/manifests/$app_name/overlays/$cluster/values-overrides.yaml"
      values_overlay_dir="gitops/manifests/$app_name/overlays/$cluster"

      export APPLICATION_NAME="$app_name"
      export ARGOCD_NAMESPACE="$argocd_namespace"
      export CLUSTER_NAME="$cluster"
      export DESTINATION_SERVER="$destination_server"
      export VALUES_REPO_URL="$values_repo_url"
      export VALUES_TARGET_REVISION="$values_target_revision"
      # shellcheck disable=SC2016
      export VALUES_REF='$values'
      export VALUES_COMMON_FILE="$values_common_file"
      export VALUES_OVERLAY_FILE="$values_overlay_file"
      export VALUES_OVERLAY_DIR="$values_overlay_dir"

      envsubst <"$template_path" >"$applications_dir/$app_file"
    done
  done
}

if [[ "$check" == true ]]; then
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' EXIT

  mkdir -p "$tmpdir"
  cp -R "$repo_root/gitops" "$tmpdir/gitops"
  generate "$tmpdir"

  diff -ru "$repo_root/gitops/clusters" "$tmpdir/gitops/clusters"
else
  generate "$repo_root"
fi
