name: Test NixOS Runners

on: [push, pull_request]

jobs:
  test_on_dsqr1:
    runs-on: [self-hosted, nixos, dsqr1]
    steps:
      - name: Print NixOS version
        run: nixos-version
      - name: Log runner information
        run: echo "Running on runner: ${{ env.RUNNER_NAME }}"

  test_on_dsqr2:
    runs-on: [self-hosted, nixos, dsqr2]
    steps:
      - name: Print NixOS version
        run: nixos-version
      - name: Log runner information
        run: echo "Running on runner: ${{ env.RUNNER_NAME }}"