/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HomelabIndexRouteImport } from './routes/homelab/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogNewRouteImport } from './routes/blog/new'
import { Route as BlogPostIdRouteImport } from './routes/blog/$postId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiPostsSlugImagesFileNameRouteImport } from './routes/api/posts.$slug.images.$fileName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomelabIndexRoute = HomelabIndexRouteImport.update({
  id: '/homelab/',
  path: '/homelab/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsSlugImagesFileNameRoute =
  ApiPostsSlugImagesFileNameRouteImport.update({
    id: '/api/posts/$slug/images/$fileName',
    path: '/api/posts/$slug/images/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/new': typeof BlogNewRoute
  '/blog': typeof BlogIndexRoute
  '/homelab': typeof HomelabIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/social': typeof SocialIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/posts/$slug/images/$fileName': typeof ApiPostsSlugImagesFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/new': typeof BlogNewRoute
  '/blog': typeof BlogIndexRoute
  '/homelab': typeof HomelabIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/social': typeof SocialIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/posts/$slug/images/$fileName': typeof ApiPostsSlugImagesFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/new': typeof BlogNewRoute
  '/blog/': typeof BlogIndexRoute
  '/homelab/': typeof HomelabIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/social/': typeof SocialIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/posts/$slug/images/$fileName': typeof ApiPostsSlugImagesFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$postId'
    | '/blog/new'
    | '/blog'
    | '/homelab'
    | '/settings'
    | '/social'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/posts/$slug/images/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$postId'
    | '/blog/new'
    | '/blog'
    | '/homelab'
    | '/settings'
    | '/social'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/posts/$slug/images/$fileName'
  id:
    | '__root__'
    | '/'
    | '/blog/$postId'
    | '/blog/new'
    | '/blog/'
    | '/homelab/'
    | '/settings/'
    | '/social/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/posts/$slug/images/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  BlogNewRoute: typeof BlogNewRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HomelabIndexRoute: typeof HomelabIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SocialIndexRoute: typeof SocialIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiPostsSlugImagesFileNameRoute: typeof ApiPostsSlugImagesFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homelab/': {
      id: '/homelab/'
      path: '/homelab'
      fullPath: '/homelab'
      preLoaderRoute: typeof HomelabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$slug/images/$fileName': {
      id: '/api/posts/$slug/images/$fileName'
      path: '/api/posts/$slug/images/$fileName'
      fullPath: '/api/posts/$slug/images/$fileName'
      preLoaderRoute: typeof ApiPostsSlugImagesFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  BlogNewRoute: BlogNewRoute,
  BlogIndexRoute: BlogIndexRoute,
  HomelabIndexRoute: HomelabIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SocialIndexRoute: SocialIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiPostsSlugImagesFileNameRoute: ApiPostsSlugImagesFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
