/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSocialIndexRouteImport } from './routes/_authenticated/social/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHomelabIndexRouteImport } from './routes/_authenticated/homelab/index'
import { Route as AuthenticatedBlogIndexRouteImport } from './routes/_authenticated/blog/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthenticatedBlogNewRouteImport } from './routes/_authenticated/blog/new'
import { Route as AuthenticatedBlogPostIdRouteImport } from './routes/_authenticated/blog/$postId'
import { Route as ApiPostsSlugImagesFileNameRouteImport } from './routes/api/posts.$slug.images.$fileName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSocialIndexRoute =
  AuthenticatedSocialIndexRouteImport.update({
    id: '/social/',
    path: '/social/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomelabIndexRoute =
  AuthenticatedHomelabIndexRouteImport.update({
    id: '/homelab/',
    path: '/homelab/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlogIndexRoute = AuthenticatedBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBlogNewRoute = AuthenticatedBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlogPostIdRoute = AuthenticatedBlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPostsSlugImagesFileNameRoute =
  ApiPostsSlugImagesFileNameRouteImport.update({
    id: '/api/posts/$slug/images/$fileName',
    path: '/api/posts/$slug/images/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/blog/$postId': typeof AuthenticatedBlogPostIdRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/blog': typeof AuthenticatedBlogIndexRoute
  '/homelab': typeof AuthenticatedHomelabIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/social': typeof AuthenticatedSocialIndexRoute
  '/api/posts/$slug/images/$fileName': typeof ApiPostsSlugImagesFileNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/blog/$postId': typeof AuthenticatedBlogPostIdRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/blog': typeof AuthenticatedBlogIndexRoute
  '/homelab': typeof AuthenticatedHomelabIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/social': typeof AuthenticatedSocialIndexRoute
  '/api/posts/$slug/images/$fileName': typeof ApiPostsSlugImagesFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/blog/$postId': typeof AuthenticatedBlogPostIdRoute
  '/_authenticated/blog/new': typeof AuthenticatedBlogNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/blog/': typeof AuthenticatedBlogIndexRoute
  '/_authenticated/homelab/': typeof AuthenticatedHomelabIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/social/': typeof AuthenticatedSocialIndexRoute
  '/api/posts/$slug/images/$fileName': typeof ApiPostsSlugImagesFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/blog/$postId'
    | '/blog/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/blog'
    | '/homelab'
    | '/settings'
    | '/social'
    | '/api/posts/$slug/images/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/blog/$postId'
    | '/blog/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/blog'
    | '/homelab'
    | '/settings'
    | '/social'
    | '/api/posts/$slug/images/$fileName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/blog/$postId'
    | '/_authenticated/blog/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/blog/'
    | '/_authenticated/homelab/'
    | '/_authenticated/settings/'
    | '/_authenticated/social/'
    | '/api/posts/$slug/images/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiPostsSlugImagesFileNameRoute: typeof ApiPostsSlugImagesFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social/': {
      id: '/_authenticated/social/'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/homelab/': {
      id: '/_authenticated/homelab/'
      path: '/homelab'
      fullPath: '/homelab'
      preLoaderRoute: typeof AuthenticatedHomelabIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog/': {
      id: '/_authenticated/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/blog/new': {
      id: '/_authenticated/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof AuthenticatedBlogNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog/$postId': {
      id: '/_authenticated/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof AuthenticatedBlogPostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/posts/$slug/images/$fileName': {
      id: '/api/posts/$slug/images/$fileName'
      path: '/api/posts/$slug/images/$fileName'
      fullPath: '/api/posts/$slug/images/$fileName'
      preLoaderRoute: typeof ApiPostsSlugImagesFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBlogPostIdRoute: typeof AuthenticatedBlogPostIdRoute
  AuthenticatedBlogNewRoute: typeof AuthenticatedBlogNewRoute
  AuthenticatedBlogIndexRoute: typeof AuthenticatedBlogIndexRoute
  AuthenticatedHomelabIndexRoute: typeof AuthenticatedHomelabIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSocialIndexRoute: typeof AuthenticatedSocialIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBlogPostIdRoute: AuthenticatedBlogPostIdRoute,
  AuthenticatedBlogNewRoute: AuthenticatedBlogNewRoute,
  AuthenticatedBlogIndexRoute: AuthenticatedBlogIndexRoute,
  AuthenticatedHomelabIndexRoute: AuthenticatedHomelabIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSocialIndexRoute: AuthenticatedSocialIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiPostsSlugImagesFileNameRoute: ApiPostsSlugImagesFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
