apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dsqr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: dsqr
    app.kubernetes.io/part-of: dsqr-gitops
    homelab.dev/tier: apps
spec:
  description: dsqr.dev application workloads
  sourceRepos:
    - https://github.com/0xdsqr/dsqr-dotdev.git
    - https://github.com/0xdsqr/fidara.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: dsqr
    - server: https://kubernetes.default.svc
      namespace: fidara
    - server: https://kubernetes.default.svc
      namespace: twt
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
