apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dsqr
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: dsqr-gitops
spec:
  description: dsqr.dev application workloads
  sourceRepos:
    - https://github.com/0xdsqr/dsqr-dotdev.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: dsqr
    - server: https://kubernetes.default.svc
      namespace: twt
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
