apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: dsqr-gitops
spec:
  description: Homelab cluster platform add-ons
  sourceRepos:
    - https://github.com/0xdsqr/dsqr-dotdev.git
    - https://helm.cilium.io/
    - https://metallb.github.io/metallb
    - https://traefik.github.io/charts
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: metallb-system
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: observability
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
