name: Check

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Run checks
        run: nix flake check

  build-images:
    name: build
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build dotdev image
        run: nix build .#dotdevImage --out-link result-dotdev

      - name: Build studio image
        run: nix build .#studioImage --out-link result-studio

      - name: Build labs image
        run: nix build .#labsImage --out-link result-labs
